### ISSUE TITLE
Support for Knockout 3.5.x

### ISSUE THREAD

**Issue by peppertech** [Spreetail/knockout-store#10]
Hello, there appears to be some dependency on Knockout 3.4.67 at the moment.  This release of KO has known security issues.  Are there plans to update the dependency to use KO 3.5.0 or the latest 3.5.1?  Thanks

**Comment by blyry** [comment]
Hi @peppertech, I don't believe there are any plans, neither of the creators work at spreetail anymore and most of our pages w/ knockout have been either migrated to something newer and fully react based, OR are EOL and in maintenance mode. If you make a PR I could rustle up someone to look at it quick though!

**Comment by blyry** [comment]
cc @daltonwignall @metalex9 do you guys have any interest in maintaining this?

**Comment by alexbainter** [comment]
Hey @peppertech. Since Knockout is a dev dependency of this lib it shouldn't be installed by npm when you add this package, nor is Knockout included in the script file. This definitely should be updated, but in the meantime it remains safe to use.

@blyry Yeah I can watch over this!

**Comment by alexbainter** [comment]
Oh @peppertech were you seeing the dependency for [@types/knockout@3.4.67](https://www.npmjs.com/package/@types/knockout)? Those are just TypeScript types for that version of Knockout -- also totally safe to use.

**Comment by peppertech** [comment]
Thanks guys.  The issue we have is that the reference to the TypeDefs is for Knockout 3.4.67, but in our app we are required to use KO 3.5+ because of existing security vulnerabilities in older KO versions.  Unfortunately, when KO released 3.5.0 they also updated their *.d.ts files and started shipping them with their distribution instead of hosting them on definitelyTyped.  There are conflicts between the two definition files so you can't mix them.

Hope that makes sense.

**Comment by alexbainter** [comment]
Ooooh I see, I was wondering why there was no update for that package. If the types are included with Knockout now I can just remove that typedef and publish a new version. Thanks for bringing this up.

**Comment by peppertech** [comment]
Be careful that you test the library with the new typedefs that are included with KO 3.5+ because they changed types and there may be some updates to the library required.  We ran into this last year with our own project.  I'm the manager for Oracle's JavaScript Extension Toolkit (JET)  https://oracle.com/jet

**Comment by alexbainter** [comment]
@peppertech I just published version 4.0.0 with new type definitions, want to give that a try?

**Comment by peppertech** [comment]
Thanks, I'll pull the new version and give it a spin!

**Comment by sanojantony-oracle** [comment]
@peppertech @metalex9 @blyry 
Tried the new release with our app. Everything looks good! No conflicting type definitions anymore with KO 3.5.x. Thx much!
